apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ .Values.cast_db.name }}
spec:
  accessModes:
    - {{ .Values.cast_db.pvc.accessMode }}
  storageClassName: {{ .Values.cast_db.pvc.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.cast_db.pvc.storage }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cast_db.name }}
type: Opaque
data:
  POSTGRES_DB: {{ .Values.cast_db.secret.db | b64enc }}
  POSTGRES_USER: {{ .Values.cast_db.secret.username | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.cast_db.secret.password | b64enc }}

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-{{ .Values.cast_db.name }}
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .Values.cast_db.deployment.kind }}
    name: {{ .Values.cast_db.name }}
  minReplicas: {{ .Values.cast_db.hpa.minReplicas }}
  maxReplicas: {{ .Values.cast_db.hpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.cast_db.hpa.targetCPUUtilizationPercentage }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cast_db.name }}
spec:
  type: {{ .Values.cast_db.service.type }}
  selector:
    app: {{ .Values.cast_db.name }}
  ports:
    - protocol: {{ .Values.cast_db.service.protocol }}
      port: {{ .Values.cast_db.service.port }}
      targetPort: {{ .Values.cast_db.service.targetPort }}
      nodePort: {{ .Values.cast_db.service.nodePort }} 

---

apiVersion: apps/v1
kind: {{ .Values.cast_db.deployment.kind }}
metadata:
  name: {{ .Values.cast_db.name }}
  labels:
    app: {{ .Values.cast_db.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.cast_db.name }}
  replicas: {{ .Values.cast_db.deployment.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.cast_db.name }}
    spec:
      containers:
        - name: {{ .Values.cast_db.deployment.name }}
          image: "{{ .Values.cast_db.deployment.image.repository }}:{{ .Values.cast_db.deployment.image.tag | default .Values.imageTag }}"
          ports:
            - containerPort: {{ .Values.cast_db.deployment.ports }}
          volumeMounts:
            - name: db
              mountPath: /var/lib/postgresql/data/
          envFrom:
            - secretRef:
                name: {{ .Values.cast_db.name }}
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: pvc-{{ .Values.cast_db.name }}
