# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullSecrets:
  - name: regcred

movie_service:
  name: movie_service
  deployment:
    kind: Deployment
    name: movie_service
    image:
      repository: "apooz/jenkins-exam-movie_service"
      tag: ""
    replicaCount: 3
    ports: 8000
  hpa:
    minReplicas: 3
    maxReplicas: 6
    targetCPUUtilizationPercentage: 70
  service:
    type: ClusterIP
    protocol: TCP
    port: 8001
  pvc:
    accessMode: ReadWriteOnce
    storage: 10Gi
    storageClassName: local-path  

movie_db:
  name: movie_db
  deployment:
    kind: StatefulSets
    name: movie_db
    image:
      repository: "postgres"
      tag: "12.1-alpine"
    replicaCount: 3
    ports: 5432
  hpa:
    minReplicas: 3
    maxReplicas: 6
    targetCPUUtilizationPercentage: 70
  service:
    type: ClusterIP
    protocol: TCP
    port: 5432
  pvc:
    accessMode: ReadWriteOnce
    storage: 10Gi
    storageClassName: local-path  
  secret:
    db: ''
    username: ''
    password: ''

cast_service:
  name: cast_service
  deployment:
    kind: Deployment
    name: cast_service
    image:
      repository: "apooz/jenkins-exam-cast_service"
      tag: ""
    replicaCount: 3
    ports: 8000
  hpa:
    minReplicas: 3
    maxReplicas: 6
    targetCPUUtilizationPercentage: 70
  service:
    type: ClusterIP
    protocol: TCP
    port: 8002
  pvc:
    accessMode: ReadWriteOnce
    storage: 10Gi
    storageClassName: local-path  

cast_db:
  name: cast_db
  deployment:
    kind: StatefulSets
    name: cast_db
    image:
      repository: "postgres"
      tag: "12.1-alpine"
    replicaCount: 3
    ports: 5432
  hpa:
    minReplicas: 3
    maxReplicas: 6
    targetCPUUtilizationPercentage: 70
  service:
    type: ClusterIP
    protocol: TCP
    port: 5432
  pvc:
    accessMode: ReadWriteOnce
    storage: 10Gi
    storageClassName: local-path  
  secret:
    db: ''
    username: ''
    password: ''


nginx:
  name: nginx
  deployment:
    kind: Deployment
    name: nginx
    image:
      repository: "nginx"
      tag: "latest"
    replicaCount: 3
    ports: 8080
  hpa:
    minReplicas: 3
    maxReplicas: 6
    targetCPUUtilizationPercentage: 70
  service:
    type: NodePort
    protocol: TCP
    port: 8080
