# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullSecrets:
  - name: regcred

movie-service:
  name: movie-service
  deployment:
    kind: Deployment
    name: movie-service
    image:
      repository: "apooz/jenkins-exam-movie-service"
      tag: ""
    replicaCount: 3
    ports: 8000
  hpa:
    minReplicas: 3
    maxReplicas: 6
    targetCPUUtilizationPercentage: 70
  service:
    type: ClusterIP
    protocol: TCP
    port: 8001
  pvc:
    accessMode: ReadWriteOnce
    storage: 10Gi
    storageClassName: local-path  

movie-db:
  name: movie-db
  deployment:
    kind: StatefulSet
    name: movie-db
    image:
      repository: "postgres"
      tag: "12.1-alpine"
    replicaCount: 3
    ports: 5432
  hpa:
    minReplicas: 3
    maxReplicas: 6
    targetCPUUtilizationPercentage: 70
  service:
    type: ClusterIP
    protocol: TCP
    port: 5432
  pvc:
    accessMode: ReadWriteOnce
    storage: 10Gi
    storageClassName: local-path  
  secret:
    db: movie-db-dev
    username: movie_db_username
    password: movie_db_password

cast-service:
  name: cast-service
  deployment:
    kind: Deployment
    name: cast-service
    image:
      repository: "apooz/jenkins-exam-cast-service"
      tag: ""
    replicaCount: 3
    ports: 8000
  hpa:
    minReplicas: 3
    maxReplicas: 6
    targetCPUUtilizationPercentage: 70
  service:
    type: ClusterIP
    protocol: TCP
    port: 8002
  pvc:
    accessMode: ReadWriteOnce
    storage: 10Gi
    storageClassName: local-path  

cast-db:
  name: cast-db
  deployment:
    kind: StatefulSet
    name: cast-db
    image:
      repository: "postgres"
      tag: "12.1-alpine"
    replicaCount: 3
    ports: 5432
  hpa:
    minReplicas: 3
    maxReplicas: 6
    targetCPUUtilizationPercentage: 70
  service:
    type: ClusterIP
    protocol: TCP
    port: 5432
  pvc:
    accessMode: ReadWriteOnce
    storage: 10Gi
    storageClassName: local-path
  secret:
    db: cast_db_dev
    username: cast_db_username
    password: cast_db_password

nginx:
  name: nginx
  deployment:
    kind: Deployment
    name: nginx
    image:
      repository: "nginx"
      tag: "latest"
    replicaCount: 3
    ports: 8080
  hpa:
    minReplicas: 3
    maxReplicas: 6
    targetCPUUtilizationPercentage: 70
  service:
    type: NodePort
    protocol: TCP
    port: 8080
